production: &default
  adapter: postgresql
  database: awesomefoundation_production
  pool: <%= ENV['DB_POOL'] || ENV['RAILS_MAX_THREADS'] || 5 %>
  timeout: 5000

<% if Rails.env.development? %>
development: &default
  adapter: postgresql
  database: <%= ENV['DB_NAME'] || 'awesomefoundation_development' %>
  pool: 5
  timeout: 5000
  host: <%= ENV['POSTGRES_HOST'] || 'localhost' %>
  username: <%= ENV['POSTGRES_USER'] || '' %>
  password: <%= ENV['POSTGRES_PASSWORD'] || '' %>
<% end %>

test: &test
  <<: *default
  database: awesomefoundation_test
  host: <%= ENV['POSTGRES_HOST'] || 'localhost' %>
  username: <%= ENV['POSTGRES_USER'] || '' %>
  password: <%= ENV['POSTGRES_PASSWORD'] || '' %>
  min_messages: warning

cucumber:
  <<: *test
