# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5e8bc6ddaae643f6959d086887161da6c00d4f2dc7cbf75ab730e04e29a801d4df8c7c3b350e70cbee21111887b41eb3928106904b94ccdf41c9818edbf2418
  secret_token: b2a107adc992f44e3664aef41a706038428ac8cf73588f25956181fcf47ec2a6aa1df1cad5c74bea41ec6dd3bad088b6d18225f776bb57c4b6a53a92977b9206

test:
  secret_key_base: e83a59dc675d7245457362366635b42f3ac78b2f1382a1005e0a6e3ec0d62c2db74b950304bc8ec6f87a2cc71e80aab65dde8fbc0cab2c163fdb2dc9e6024f42
  secret_token: 8625412fbf7a8d02bb01a585e640cd484c065feb0384235b1def029d0839b70cb703e8af8a1343591b1c473db6454d813127977bf6e906603cc20c4737b57cf1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_token: <%= ENV["SECRET_TOKEN"] %>
